### PR TITLE
Avoid deprecated warnings: use enum value instead of 0

### PR DESCRIPTION
**Pull request by dlrdave**

### CODE REVIEW

**Comment by faaxm** [comment]
LGTM, but please run clang-format with `./devtools/run-clang-format.sh` (or manually). Thank you!

**Comment by dlrdave** [comment]
> LGTM, but please run clang-format with `./devtools/run-clang-format.sh` (or manually). Thank you!

When I run `./devtools/run-clang-format.sh` (with clang-format v3.8.0 installed on my older and only Ubuntu machine), I get a substantially different source tree. I also get "unknown enumerated scalar" errors about the InlineOnly setting in .clang-format.

Is this clang-format too old?

I'll push up a commit that contains the formatting changes just for this one source file. It's a substantial diff, although presumably only stylistic.

**Comment by faaxm** [comment]
Hmmm, this doesn't look right. It is important that you run this command from the spix root folder, where the `.clang-format` file is that defines the formatting.
It looks like your clang-format used some other, default formatting instead.

You can have a look at the "Verify Formatting" check of the CI pipeline. Not sure if it is accessible for you, but the output of the first run is here and in the diff you see that clang-format should only change the lines you edited:
https://github.com/faaxm/spix/runs/3311805557

**Comment by faaxm** [comment]
Thank you @dlrdave for looking into this, but I got another PR ( #42 )for this issue in the meantime and merged that one.

**Comment by dlrdave** [comment]
> Thank you @dlrdave for looking into this, but I got another PR ( #42 )for this issue in the meantime and merged that one.

You're welcome. Thank YOU for merging #42.

**Pull request closed without merging**
